changes.md
igoradamenko/awsm.css pull request #104
Opened 2020-09-30 18:48 UTC by Vishwa0302

2020-09-30 19:06 UTC, igoradamenko requested changes

2020-09-30 19:06 UTC, igoradamenko commented on README.md
> +for reference i sometimes referrer to (https://www.w3schools.com/html/)
Wut?

2020-10-01 10:28 UTC, Vishwa0302 commented
Because the link has good information about web development

On Thu, 1 Oct 2020, 12:37 am Igor Adamenko, <notifications@github.com>
wrote:

> *@igoradamenko* requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/igoradamenko/awsm.css/pull/104#discussion_r497737516>:
>
> > @@ -87,6 +87,7 @@ The MIT License places almost no restrictions on what you can do with this lib.
>  [Website for this repo](https://igoradamenko.github.io/awsm.css/) uses awsm.css. Check this out. Also there are examples of [blog](https://igoradamenko.github.io/awsm.css/examples/blog/) and [homepage](https://igoradamenko.github.io/awsm.css/examples/homepage/) built with awsm.css.
>
>  And I use the lib for [my own website](https://igoradamenko.com).
> +for reference i sometimes referrer to (https://www.w3schools.com/html/)
>
> Wut?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/igoradamenko/awsm.css/pull/104#pullrequestreview-499730434>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOTECG4VO6HM5GRK2WJULN3SIN6VZANCNFSM4R7OOMUQ>
> .
>

2020-10-01 10:35 UTC, igoradamenko commented
Sorry, it does not make any sense.

2020-10-01 10:35 UTC, closed without merging